"""The song as every reader leaves it (the IR) and the one walk that plays it: SMPS's vocabulary,
whatever driver or file the song came from.

    song.py           SmpsSong and its parts (the parser's output)
    effects.py        CoordFlag and its effects, one frozen class per flag: SetVoice(index) ...
    code.py           SmpsCode: a song's track code as ops; song_from_code, the one walk to events
    driver_track.py   DriverTrack: what a track's driver does to its effects and notes (TrackRules)
    voice_patch.py    VoicePatcher: a song's voices with its tracks' register writes over them
    run_out.py        apply_run_out: a driver's key-on run-out, after the walk
    parser.py         SmpsParser: assembly -> SmpsCode -> SmpsSong
    asm_writer.py     write_asm: SongCode -> SMPS2ASM assembly (SmpsParser reads it back)
    song_prep.py      prepare_song: a new song as the driver plays it (tempo dividers, short loops replayed)
    driver_tables.py  the driver's frequency tables, note indices, envelopes, operator order
    names.py          note labels, config pitch names, DAC names, SFX channel ids, source channel names
    track.py          TrackState: one track's driver state as its coordination flags leave it
    tempo.py          TempoSegment, tempo_schedule: the frame each tick is read on
    playback.py       played_song: what a song plays note by note, its spelling gone
    compare.py        compare_songs: where two songs play differently, aspect by aspect;
                      parse_differences: where two readings of the same bytes differ
"""

from .asm_writer import write_asm
from .code import (
    TRACK_BYTES,
    Op,
    OpKind,
    SmpsCode,
    SongCode,
    effect_from_bytes,
    song_from_code,
    track_byte,
)
from .compare import ALL_ASPECTS, ChannelDiff, NoteDiff, SongDiff, align_songs, compare_songs, parse_differences
from .driver_tables import (
    C1_SEMITONE,
    FM_SLOT_MASK,
    HW_FM_CHANNEL,
    PAN_VALUES,
    PSG_CHANNEL,
    SMPS_OP_TO_REG_OFFSET,
    PsgEnvelope,
    chip_pitch,
    fm_note_index,
    fm_table_index,
    noise_envelope_frames,
    psg_index_semitone,
    psg_note_index,
    psg_tone2_divider,
    psg_voice_name,
    signed_byte,
)
from .effects import (
    AlterVol,
    AlterVolumeStep,
    ChangeTransposition,
    ChanTempoDiv,
    CoordFlag,
    Detune,
    DetuneAdd,
    DriverEffect,
    Gate,
    ModOff,
    ModOn,
    ModSet,
    Nop,
    NoteFill,
    Pan,
    PlayedEffect,
    PsgForm,
    PsgVoice,
    SelectSample,
    SetTempoDiv,
    SetTempoMod,
    SetVoice,
    SetVol,
    SmpsEffect,
    VoiceRegister,
    VolumeStep,
    effect_of,
    pan_is_hard,
    pan_side,
)
from .names import (
    FM_CHANNEL_NAMES,
    PSG_CHANNEL_NAMES,
    SFX_CHANNEL_IDS,
    SMPS_DAC_NAMES,
    flag_from_macro,
    flag_name,
    note_label,
    parse_smps_note,
    parse_synth_note,
    semitone_to_note_name,
    source_map,
    source_names,
    synth_note_name,
    voice_field_from_macro,
)
from .parser import SmpsParser
from .percussion import FmDrum, FmFrame
from .playback import Aspect, PlayedNote, PlayedSong, played_song
from .rules import PlaybackRules, TrackRules
from .song import (
    FIRST_FLAG,
    FIRST_NOTE,
    LAST_NOTE,
    MAX_PSG,
    REGISTER_FIELDS,
    REST,
    SELECTED_SAMPLE,
    ChannelType,
    SmpsChannel,
    SmpsChannelHeader,
    SmpsEvent,
    SmpsNote,
    SmpsSong,
    SmpsSongHeader,
    SmpsVoice,
    VoiceField,
)
from .song_prep import PreparedSong, prepare_song
from .tempo import NO_TEMPO_HOLDS, TempoSegment, frame_of_tick, tempo_schedule, tick_at_frame
from .track import TrackState

__all__ = [
    "ALL_ASPECTS",
    "C1_SEMITONE",
    "FIRST_FLAG",
    "FIRST_NOTE",
    "FM_CHANNEL_NAMES",
    "FM_SLOT_MASK",
    "HW_FM_CHANNEL",
    "LAST_NOTE",
    "MAX_PSG",
    "NO_TEMPO_HOLDS",
    "PAN_VALUES",
    "PSG_CHANNEL",
    "PSG_CHANNEL_NAMES",
    "REGISTER_FIELDS",
    "REST",
    "SELECTED_SAMPLE",
    "SFX_CHANNEL_IDS",
    "SMPS_DAC_NAMES",
    "SMPS_OP_TO_REG_OFFSET",
    "TRACK_BYTES",
    "AlterVol",
    "AlterVolumeStep",
    "Aspect",
    "ChanTempoDiv",
    "ChangeTransposition",
    "ChannelDiff",
    "ChannelType",
    "CoordFlag",
    "Detune",
    "DetuneAdd",
    "DriverEffect",
    "FmDrum",
    "FmFrame",
    "Gate",
    "ModOff",
    "ModOn",
    "ModSet",
    "Nop",
    "NoteDiff",
    "NoteFill",
    "Op",
    "OpKind",
    "Pan",
    "PlaybackRules",
    "PlayedEffect",
    "PlayedNote",
    "PlayedSong",
    "PreparedSong",
    "PsgEnvelope",
    "PsgForm",
    "PsgVoice",
    "SelectSample",
    "SetTempoDiv",
    "SetTempoMod",
    "SetVoice",
    "SetVol",
    "SmpsChannel",
    "SmpsChannelHeader",
    "SmpsCode",
    "SmpsEffect",
    "SmpsEvent",
    "SmpsNote",
    "SmpsParser",
    "SmpsSong",
    "SmpsSongHeader",
    "SmpsVoice",
    "SongCode",
    "SongDiff",
    "TempoSegment",
    "TrackRules",
    "TrackState",
    "VoiceField",
    "VoiceRegister",
    "VolumeStep",
    "align_songs",
    "chip_pitch",
    "compare_songs",
    "effect_from_bytes",
    "effect_of",
    "flag_from_macro",
    "flag_name",
    "fm_note_index",
    "fm_table_index",
    "frame_of_tick",
    "noise_envelope_frames",
    "note_label",
    "pan_is_hard",
    "pan_side",
    "parse_differences",
    "parse_smps_note",
    "parse_synth_note",
    "played_song",
    "prepare_song",
    "psg_index_semitone",
    "psg_note_index",
    "psg_tone2_divider",
    "psg_voice_name",
    "semitone_to_note_name",
    "signed_byte",
    "song_from_code",
    "source_map",
    "source_names",
    "synth_note_name",
    "tempo_schedule",
    "tick_at_frame",
    "track_byte",
    "voice_field_from_macro",
    "write_asm",
]
