"""The source: Sonic 1 SMPS songs and the driver that plays them.

    song.py           SmpsSong and its parts (the parser's output)
    code.py           SmpsCode: a song's track code as ops; song_from_code, the one walk to events
    parser.py         SmpsParser: assembly -> SmpsCode -> SmpsSong
    asm_writer.py     write_asm: SongCode -> SMPS2ASM assembly (SmpsParser reads it back)
    song_prep.py      the song as the driver plays it (tempo-divider re-timing, short loops replayed)
    driver_tables.py  the driver's frequency tables, note indices, envelopes, operator order
    names.py          note labels, config pitch names, DAC names, SFX channel ids, source channel names
    track.py          TrackState: one track's driver state as its coordination flags leave it
    tempo.py          TempoSegment, tempo_schedule: the frame each tick is read on
    playback.py       played_song: what a song plays note by note, its spelling gone
    compare.py        compare_songs: where two songs play differently, aspect by aspect;
                      parse_differences: where two readings of the same bytes differ
"""

from .asm_writer import write_asm
from .code import (
    FIRST_FLAG,
    FIRST_NOTE,
    LAST_NOTE,
    TRACK_BYTES,
    Op,
    OpKind,
    SmpsCode,
    SongCode,
    effect_from_bytes,
    signed_byte,
    song_from_code,
    track_byte,
)
from .compare import ALL_ASPECTS, ChannelDiff, NoteDiff, SongDiff, align_songs, compare_songs, parse_differences
from .driver_tables import (
    C1_SEMITONE,
    DEFAULT_DRIVER,
    ENVELOPE_TERMINATOR,
    FM_FREQUENCIES,
    FM_SLOT_MASK,
    HW_FM_CHANNEL,
    PAN_VALUES,
    PSG_CHANNEL,
    PSG_ENVELOPES,
    PSG_ENVELOPES_BY_NAME,
    PSG_FREQUENCIES,
    PSG_FREQUENCIES_EXTENDED,
    SMPS_OP_TO_REG_OFFSET,
    SONIC1_ENVELOPES,
    PsgEnvelope,
    SmpsDriver,
    chip_pitch,
    fm_note_index,
    fm_table_index,
    noise_envelope_frames,
    psg_index_semitone,
    psg_note_index,
    psg_tone2_divider,
    psg_voice_name,
)
from .names import (
    SFX_CHANNEL_IDS,
    SMPS_DAC_NAMES,
    flag_from_macro,
    flag_name,
    note_label,
    parse_smps_note,
    parse_synth_note,
    semitone_to_note_name,
    source_map,
    source_names,
    synth_note_name,
    voice_field_from_macro,
)
from .parser import SmpsParser
from .percussion import FmDrum, FmFrame
from .playback import Aspect, PlayedNote, PlayedSong, played_song
from .song import (
    REST,
    ChannelType,
    CoordFlag,
    SmpsChannel,
    SmpsChannelHeader,
    SmpsEffect,
    SmpsEvent,
    SmpsNote,
    SmpsSong,
    SmpsSongHeader,
    SmpsVoice,
    VoiceField,
    pan_is_hard,
    pan_side,
)
from .song_prep import apply_global_tempo_div, extend_looping_channels
from .tempo import NO_TEMPO_HOLDS, TempoSegment, frame_of_tick, tempo_schedule, tick_at_frame
from .track import TrackState

__all__ = [
    "ALL_ASPECTS",
    "C1_SEMITONE",
    "DEFAULT_DRIVER",
    "ENVELOPE_TERMINATOR",
    "FIRST_FLAG",
    "FIRST_NOTE",
    "FM_FREQUENCIES",
    "FM_SLOT_MASK",
    "HW_FM_CHANNEL",
    "LAST_NOTE",
    "NO_TEMPO_HOLDS",
    "PAN_VALUES",
    "PSG_CHANNEL",
    "PSG_ENVELOPES",
    "PSG_ENVELOPES_BY_NAME",
    "PSG_FREQUENCIES",
    "PSG_FREQUENCIES_EXTENDED",
    "REST",
    "SFX_CHANNEL_IDS",
    "SMPS_DAC_NAMES",
    "SMPS_OP_TO_REG_OFFSET",
    "SONIC1_ENVELOPES",
    "TRACK_BYTES",
    "Aspect",
    "ChannelDiff",
    "ChannelType",
    "CoordFlag",
    "FmDrum",
    "FmFrame",
    "NoteDiff",
    "Op",
    "OpKind",
    "PlayedNote",
    "PlayedSong",
    "PsgEnvelope",
    "SmpsChannel",
    "SmpsChannelHeader",
    "SmpsCode",
    "SmpsDriver",
    "SmpsEffect",
    "SmpsEvent",
    "SmpsNote",
    "SmpsParser",
    "SmpsSong",
    "SmpsSongHeader",
    "SmpsVoice",
    "SongCode",
    "SongDiff",
    "TempoSegment",
    "TrackState",
    "VoiceField",
    "align_songs",
    "apply_global_tempo_div",
    "chip_pitch",
    "compare_songs",
    "effect_from_bytes",
    "extend_looping_channels",
    "flag_from_macro",
    "flag_name",
    "fm_note_index",
    "fm_table_index",
    "frame_of_tick",
    "noise_envelope_frames",
    "note_label",
    "pan_is_hard",
    "pan_side",
    "parse_differences",
    "parse_smps_note",
    "parse_synth_note",
    "played_song",
    "psg_index_semitone",
    "psg_note_index",
    "psg_tone2_divider",
    "psg_voice_name",
    "semitone_to_note_name",
    "signed_byte",
    "song_from_code",
    "source_map",
    "source_names",
    "synth_note_name",
    "tempo_schedule",
    "tick_at_frame",
    "track_byte",
    "voice_field_from_macro",
    "write_asm",
]
