"""Names vulture reports that are used, in ways it cannot see (read by vulture, never imported or run).

    unittest classes   found by test discovery, not called
    ModNote members    the note names, reached by ModNote[name] / MOD_NOTE_MAP
"""
# ruff: noqa

# Fields that record what the source holds, read by nothing yet
_.note_timeout_master  # SMPS_Track's NoteTimeoutMaster, as the SFX driver's RAM mirror holds it (sfx/track.py)
mod_byte  # smpsHeaderFM / smpsHeaderPSG's modulation byte, as parsed (core/smps_parser.py)

Cs1  # unused variable (core/tables.py:17)
D1  # unused variable (core/tables.py:18)
Ds1  # unused variable (core/tables.py:19)
E1  # unused variable (core/tables.py:20)
F1  # unused variable (core/tables.py:21)
Fs1  # unused variable (core/tables.py:22)
G1  # unused variable (core/tables.py:23)
Gs1  # unused variable (core/tables.py:24)
A1  # unused variable (core/tables.py:25)
As1  # unused variable (core/tables.py:26)
B1  # unused variable (core/tables.py:27)
Cs2  # unused variable (core/tables.py:30)
D2  # unused variable (core/tables.py:31)
Ds2  # unused variable (core/tables.py:32)
E2  # unused variable (core/tables.py:33)
F2  # unused variable (core/tables.py:34)
Fs2  # unused variable (core/tables.py:35)
G2  # unused variable (core/tables.py:36)
Gs2  # unused variable (core/tables.py:37)
A2  # unused variable (core/tables.py:38)
As2  # unused variable (core/tables.py:39)
B2  # unused variable (core/tables.py:40)
Cs3  # unused variable (core/tables.py:43)
D3  # unused variable (core/tables.py:44)
Ds3  # unused variable (core/tables.py:45)
E3  # unused variable (core/tables.py:46)
F3  # unused variable (core/tables.py:47)
Fs3  # unused variable (core/tables.py:48)
G3  # unused variable (core/tables.py:49)
Gs3  # unused variable (core/tables.py:50)
As3  # unused variable (core/tables.py:52)
B3  # unused variable (core/tables.py:53)
Kinds  # unused class (tests/test_diagnostics_units.py:19)
Record  # unused class (tests/test_diagnostics_units.py:29)
KeyOffRules  # unused class (tests/test_merge_units.py:72)
CompositeKeys  # unused class (tests/test_merge_units.py:93)
Unison  # unused class (tests/test_merge_units.py:114)
Twins  # unused class (tests/test_merge_units.py:135)
Mixer  # unused class (tests/test_merge_units.py:173)
Banks  # unused class (tests/test_merge_units.py:210)
MelodicBanks  # unused class (tests/test_merge_units.py:264)
Limiter  # unused class (tests/test_merge_units.py:330)
Saturate  # unused class (tests/test_merge_units.py:357)
BankReserve  # unused class (tests/test_merge_units.py:372)
BankAlignment  # unused class (tests/test_merge_units.py:398)
Heard  # unused class (tests/test_merge_units.py:419)
Slots  # unused class (tests/test_merge_units.py:444)
MixLoop  # unused class (tests/test_merge_units.py:457)
HeardPadding  # unused class (tests/test_merge_units.py:478)
ModWriter  # unused class (tests/test_merge_units.py:491)
Dither  # unused class (tests/test_merge_units.py:518)
Narrowing  # unused class (tests/test_merge_units.py:562)
ConfigLoading  # unused class (tests/test_merge_units.py:580)
VibratoDepth  # unused class (tests/test_vibrato_depth.py:27)
