"""Names vulture reports that are used, in ways it cannot see (read by vulture, never imported or run).

    unittest classes   found by test discovery, not called
    ModNote members    the note names, reached by ModNote[name] / MOD_NOTE_MAP
"""
# ruff: noqa

# Fields that record what the source holds, read by nothing yet
_.note_timeout_master  # SMPS_Track's NoteTimeoutMaster, as the SFX driver's RAM mirror holds it (sfx/track.py)
mod_byte  # smpsHeaderFM / smpsHeaderPSG's modulation byte, as parsed (core/smps/parser.py)
total_samples  # a VGM header's sample count (core/vgm/reader.py); the reader counts its own
loop_samples  # a VGM header's loop length (core/vgm/reader.py); the reader finds the loop's start itself

Cs1  # unused variable (core/mod/notes.py:19)
D1  # unused variable (core/mod/notes.py:20)
Ds1  # unused variable (core/mod/notes.py:21)
E1  # unused variable (core/mod/notes.py:22)
F1  # unused variable (core/mod/notes.py:23)
Fs1  # unused variable (core/mod/notes.py:24)
G1  # unused variable (core/mod/notes.py:25)
Gs1  # unused variable (core/mod/notes.py:26)
A1  # unused variable (core/mod/notes.py:27)
As1  # unused variable (core/mod/notes.py:28)
B1  # unused variable (core/mod/notes.py:29)
Cs2  # unused variable (core/mod/notes.py:32)
D2  # unused variable (core/mod/notes.py:33)
Ds2  # unused variable (core/mod/notes.py:34)
E2  # unused variable (core/mod/notes.py:35)
F2  # unused variable (core/mod/notes.py:36)
Fs2  # unused variable (core/mod/notes.py:37)
G2  # unused variable (core/mod/notes.py:38)
Gs2  # unused variable (core/mod/notes.py:39)
A2  # unused variable (core/mod/notes.py:40)
As2  # unused variable (core/mod/notes.py:41)
B2  # unused variable (core/mod/notes.py:42)
Cs3  # unused variable (core/mod/notes.py:45)
D3  # unused variable (core/mod/notes.py:46)
Ds3  # unused variable (core/mod/notes.py:47)
E3  # unused variable (core/mod/notes.py:48)
F3  # unused variable (core/mod/notes.py:49)
Fs3  # unused variable (core/mod/notes.py:50)
G3  # unused variable (core/mod/notes.py:51)
Gs3  # unused variable (core/mod/notes.py:52)
As3  # unused variable (core/mod/notes.py:54)
B3  # unused variable (core/mod/notes.py:55)
Kinds  # unused class (tests/test_diagnostics_units.py:19)
Record  # unused class (tests/test_diagnostics_units.py:29)
RoundTrip  # unused class (tests/test_render_cache_units.py:20)
Stale  # unused class (tests/test_render_cache_units.py:65)
Off  # unused class (tests/test_render_cache_units.py:102)
KeyonOnsets  # unused class (tests/test_vgm_compare_units.py:18)
KeyOffRules  # unused class (tests/test_merge_units.py:72)
CompositeKeys  # unused class (tests/test_merge_units.py:93)
Unison  # unused class (tests/test_merge_units.py:114)
Twins  # unused class (tests/test_merge_units.py:135)
Mixer  # unused class (tests/test_merge_units.py:173)
Banks  # unused class (tests/test_merge_units.py:210)
MelodicBanks  # unused class (tests/test_merge_units.py:264)
Limiter  # unused class (tests/test_merge_units.py:330)
Saturate  # unused class (tests/test_merge_units.py:357)
BankReserve  # unused class (tests/test_merge_units.py:372)
BankAlignment  # unused class (tests/test_merge_units.py:398)
Heard  # unused class (tests/test_merge_units.py:419)
Slots  # unused class (tests/test_merge_units.py:444)
MixLoop  # unused class (tests/test_merge_units.py:457)
HeardPadding  # unused class (tests/test_merge_units.py:478)
ModWriter  # unused class (tests/test_merge_units.py:491)
Dither  # unused class (tests/test_merge_units.py:518)
Narrowing  # unused class (tests/test_merge_units.py:562)
ConfigLoading  # unused class (tests/test_merge_units.py:580)
VibratoDepth  # unused class (tests/test_vibrato_depth.py:27)
Reader  # unused class (tests/test_vgm_units.py)
Chips  # unused class (tests/test_vgm_units.py)
Frames  # unused class (tests/test_vgm_units.py)
